/**
 * @svrnsec/pulse — Structured Error Handling
 */

export class PulseError extends Error {
  constructor(code, message, meta = {}) {
    super(message);
    this.name = 'PulseError';
    this.code = code;
    this.meta = meta;
    this.ts = Date.now();
  }

  toJSON() {
    return {
      name: this.name,
      code: this.code,
      message: this.message,
      meta: this.meta,
      ts: this.ts
    };
  }
}

export const PulseErrorCode = Object.freeze({
  // Structural
  INVALID_PAYLOAD_STRUCTURE: 'INVALID_PAYLOAD_STRUCTURE',
  PROTOTYPE_POLLUTION_ATTEMPT: 'PROTOTYPE_POLLUTION_ATTEMPT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_TYPE: 'INVALID_TYPE',
  TIMESTAMP_OUT_OF_RANGE: 'TIMESTAMP_OUT_OF_RANGE',
  UNSUPPORTED_PROOF_VERSION: 'UNSUPPORTED_PROOF_VERSION',

  // Hash integrity
  INVALID_HASH_FORMAT: 'INVALID_HASH_FORMAT',
  HASH_MISMATCH_PAYLOAD_TAMPERED: 'HASH_MISMATCH_PAYLOAD_TAMPERED',

  // Timestamp / freshness
  PROOF_EXPIRED: 'PROOF_EXPIRED',
  PROOF_FROM_FUTURE: 'PROOF_FROM_FUTURE',
  NONCE_INVALID_OR_REPLAYED: 'NONCE_INVALID_OR_REPLAYED',

  // Jitter / scoring
  JITTER_SCORE_TOO_LOW: 'JITTER_SCORE_TOO_LOW',
  DYNAMIC_THRESHOLD_NOT_MET: 'DYNAMIC_THRESHOLD_NOT_MET',

  // Heuristic / coherence overrides
  HEURISTIC_HARD_OVERRIDE: 'HEURISTIC_HARD_OVERRIDE',
  COHERENCE_HARD_OVERRIDE: 'COHERENCE_HARD_OVERRIDE',

  // Renderer
  SOFTWARE_RENDERER_DETECTED: 'SOFTWARE_RENDERER_DETECTED',
  BLOCKLISTED_RENDERER: 'BLOCKLISTED_RENDERER',

  // Bio activity
  NO_BIO_ACTIVITY_DETECTED: 'NO_BIO_ACTIVITY_DETECTED',

  // Cross-signal forgery detection
  FORGED_SIGNAL_CV_SCORE_IMPOSSIBLE: 'FORGED_SIGNAL:CV_SCORE_IMPOSSIBLE',
  FORGED_SIGNAL_AUTOCORR_SCORE_IMPOSSIBLE: 'FORGED_SIGNAL:AUTOCORR_SCORE_IMPOSSIBLE',
  FORGED_SIGNAL_QE_SCORE_IMPOSSIBLE: 'FORGED_SIGNAL:QE_SCORE_IMPOSSIBLE',

  // Risk flags (informational, not rejection reasons)
  NONCE_FRESHNESS_NOT_CHECKED: 'NONCE_FRESHNESS_NOT_CHECKED',
  CANVAS_UNAVAILABLE: 'CANVAS_UNAVAILABLE',
  ZERO_BIO_SAMPLES: 'ZERO_BIO_SAMPLES',
  NEGATIVE_INTERFERENCE_COEFFICIENT: 'NEGATIVE_INTERFERENCE_COEFFICIENT',
  INCONSISTENCY_LOW_CV_BUT_HIGH_SCORE: 'INCONSISTENCY:LOW_CV_BUT_HIGH_SCORE',
  SUSPICIOUS_ZERO_TIMER_GRANULARITY: 'SUSPICIOUS_ZERO_TIMER_GRANULARITY',
  INCONSISTENCY_FLAT_THERMAL_BUT_HIGH_SCORE: 'INCONSISTENCY:FLAT_THERMAL_BUT_HIGH_SCORE',
  EXTREME_HURST: 'EXTREME_HURST',
  AUDIO_JITTER_TOO_FLAT: 'AUDIO_JITTER_TOO_FLAT',
});
